add coverage check

diff --git a/.github/workflows/simulator_workflow.yaml b/.github/workflows/simulator_workflow.yaml
--- a/.github/workflows/simulator_workflow.yaml
+++ b/.github/workflows/simulator_workflow.yaml
@@ -27,6 +27,12 @@ jobs:
     - name: formatting and linting
       run: |
         make format-check
-    - name: run tests
+    - name: run test coverage
       run: |
-        make test
+        make coverage >> coverage_output/coverage.info
+        LINES_COVERED=$(cat coverage_output/coverage.info | awk '/lines\.\.\./ {print $2}' | tr -d '%')
+        REQUIRED_COVERAGE=100
+        if (( $(echo "$LINES_COVERED < $REQUIRED_COVERAGE" | bc -l) )); then
+          echo "Coverage is below $REQUIRED_COVERAGE%! Failing the build."
+          exit 1
+        fi
