Add code coverage check (#2)
* add variables to test actions

* try updating clang-format

* typo in runs-on

* add sudo

* forgot checkout

* add sudo in correct spot

* format and remove unknown format key

* debugging

* cleaning up

* add space

* add meta step just to see if it works

* proper naming

* yaml -> yml

* missing .

* fix path

* specify shell

* remove run level

* remove default

* trying to get coverage to work

* got coverage working for mac

* add coverage check

* make folder first

* install lcov

* add sudo

* adjust to work on mac and ubuntu

* move more flags to mac only

* add checks for start and end time

diff --git a/.github/workflows/simulator_workflow.yaml b/.github/workflows/simulator_workflow.yaml
--- a/.github/workflows/simulator_workflow.yaml
+++ b/.github/workflows/simulator_workflow.yaml
@@ -24,9 +24,18 @@ jobs:
       run: |
         pip install clang-format
         echo "$(clang-format --version)"
+    - name: Install lcov
+      run: |
+        sudo apt-get update && sudo apt-get install lcov
     - name: formatting and linting
       run: |
         make format-check
-    - name: run tests
+    - name: run test coverage
       run: |
-        make test
+        mkdir coverage_output && make coverage >> coverage_output/coverage.info
+        LINES_COVERED=$(cat coverage_output/coverage.info | awk '/lines\.\.\./ {print $2}' | tr -d '%')
+        REQUIRED_COVERAGE=100
+        if (( $(echo "$LINES_COVERED < $REQUIRED_COVERAGE" | bc -l) )); then
+          echo "Coverage is below $REQUIRED_COVERAGE%! Failing the build."
+          exit 1
+        fi
